version: '3.8'

services:
  dev-db:
    image: prismagraphql/mongo-single-replica:4.4.3-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=test
